-- MySQL Script generated by MySQL Workbench
-- Sat Nov 21 10:59:26 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb_Catastro
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb_Catastro
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb_Catastro` DEFAULT CHARACTER SET utf8 ;
USE `mydb_Catastro` ;

-- -----------------------------------------------------
-- Table `mydb_Catastro`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_Catastro`.`Persona` (
  `DNI` VARCHAR(9) NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `fecha nacimiento` DATETIME NULL,
  `Cabeza familia` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`DNI`),
  INDEX `CabezaFamilia_idx` (`Cabeza familia` ASC) VISIBLE,
  CONSTRAINT `CabezaFamilia`
    FOREIGN KEY (`Cabeza familia`)
    REFERENCES `mydb_Catastro`.`Persona` (`DNI`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb_Catastro`.`Zona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_Catastro`.`Zona` (
  `Nombre` VARCHAR(45) NOT NULL,
  `Area` DECIMAL(10) NULL,
  `Concejal` VARCHAR(45) NULL,
  PRIMARY KEY (`Nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb_Catastro`.`Calle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_Catastro`.`Calle` (
  `Nombre` VARCHAR(45) NOT NULL,
  `Longitud` DECIMAL(10) NULL,
  `tipo` VARCHAR(45) NULL,
  `carriles` INT NULL,
  `Zona` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Nombre`),
  INDEX `Zona_idx` (`Zona` ASC) VISIBLE,
  CONSTRAINT `Zona_Zona`
    FOREIGN KEY (`Zona`)
    REFERENCES `mydb_Catastro`.`Zona` (`Nombre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb_Catastro`.`Construccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_Catastro`.`Construccion` (
  `Area` DECIMAL(10) NULL,
  `Calle` VARCHAR(45) NOT NULL,
  `Numero` INT NOT NULL,
  `CoordenadasGeograficas` VARCHAR(45) NULL,
  PRIMARY KEY (`Numero`, `Calle`),
  INDEX `Calle_idx` (`Calle` ASC) VISIBLE,
  CONSTRAINT `Calle_Calle`
    FOREIGN KEY (`Calle`)
    REFERENCES `mydb_Catastro`.`Calle` (`Nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb_Catastro`.`Bloques`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_Catastro`.`Bloques` (
  `NumeroPisos` INT NULL,
  `Area` DECIMAL(10) NULL,
  `Calle` VARCHAR(45) NOT NULL,
  `Numero` INT NOT NULL,
  PRIMARY KEY (`Calle`, `Numero`),
  INDEX `Numero_idx` (`Numero` ASC) VISIBLE,
  CONSTRAINT `Numero_Construccion`
    FOREIGN KEY (`Numero`)
    REFERENCES `mydb_Catastro`.`Construccion` (`Numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Calle_Construccion`
    FOREIGN KEY (`Calle`)
    REFERENCES `mydb_Catastro`.`Construccion` (`Calle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb_Catastro`.`Piso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_Catastro`.`Piso` (
  `PlantaYLetra` VARCHAR(6) NOT NULL,
  `area` DECIMAL(10) NULL,
  `Propietario` VARCHAR(9) NULL,
  `Numero` INT NOT NULL,
  `Calle` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`PlantaYLetra`, `Numero`, `Calle`),
  INDEX `Propietario_idx` (`Propietario` ASC) VISIBLE,
  INDEX `Numero_idx` (`Numero` ASC) VISIBLE,
  INDEX `Calle_idx` (`Calle` ASC) VISIBLE,
  CONSTRAINT `Propietario_Persona`
    FOREIGN KEY (`Propietario`)
    REFERENCES `mydb_Catastro`.`Persona` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Numero_Bloques`
    FOREIGN KEY (`Numero`)
    REFERENCES `mydb_Catastro`.`Bloques` (`Numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Calle_Bloques`
    FOREIGN KEY (`Calle`)
    REFERENCES `mydb_Catastro`.`Bloques` (`Calle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb_Catastro`.`Unifamiliar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_Catastro`.`Unifamiliar` (
  `Area` DECIMAL(10) NULL,
  `Propietario` VARCHAR(9) NULL,
  `Numero` INT NOT NULL,
  `Calle` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Calle`, `Numero`),
  INDEX `Propietario_idx` (`Propietario` ASC) VISIBLE,
  INDEX `Numero_idx` (`Numero` ASC) VISIBLE,
  CONSTRAINT `Propietario_Persona_U`
    FOREIGN KEY (`Propietario`)
    REFERENCES `mydb_Catastro`.`Persona` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Numero_Construccion_U`
    FOREIGN KEY (`Numero`)
    REFERENCES `mydb_Catastro`.`Construccion` (`Numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Calle_Construccion_U`
    FOREIGN KEY (`Calle`)
    REFERENCES `mydb_Catastro`.`Construccion` (`Calle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb_Catastro`.`PersonaVivePiso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_Catastro`.`PersonaVivePiso` (
  `DNI` VARCHAR(9) NOT NULL,
  `Numero` INT NULL,
  `PlantaYLetra` VARCHAR(6) NULL,
  `Calle` VARCHAR(45) NULL,
  PRIMARY KEY (`DNI`),
  INDEX `Localizacion_idx` (`Numero` ASC, `PlantaYLetra` ASC, `Calle` ASC) VISIBLE,
  CONSTRAINT `DNI_Persona`
    FOREIGN KEY (`DNI`)
    REFERENCES `mydb_Catastro`.`Persona` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Localizacion_Piso`
    FOREIGN KEY (`Numero` , `PlantaYLetra` , `Calle`)
    REFERENCES `mydb_Catastro`.`Piso` (`Numero` , `PlantaYLetra` , `Calle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb_Catastro`.`PersonaViveUnifamiliar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_Catastro`.`PersonaViveUnifamiliar` (
  `DNI` VARCHAR(9) NOT NULL,
  `Numero` INT NULL,
  `Calle` VARCHAR(45) NULL,
  PRIMARY KEY (`DNI`),
  INDEX `Localizacion_idx` (`Numero` ASC, `Calle` ASC) VISIBLE,
  CONSTRAINT `DNI_Persona_U`
    FOREIGN KEY (`DNI`)
    REFERENCES `mydb_Catastro`.`Persona` (`DNI`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Localizacion_Unifamiliar`
    FOREIGN KEY (`Numero` , `Calle`)
    REFERENCES `mydb_Catastro`.`Unifamiliar` (`Numero` , `Calle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `mydb_Catastro`;

DELIMITER $$
USE `mydb_Catastro`$$
CREATE DEFINER = CURRENT_USER TRIGGER `mydb_Catastro`.`PersonaVivePiso_BEFORE_INSERT` BEFORE INSERT ON `PersonaVivePiso` FOR EACH ROW
BEGIN
	IF (NEW.DNI IN (SELECT DNI
		FROM PersonaViveUnifamiliar)) THEN
			SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = "La persona con el DNI añadido ya vive en una vivienda unifamiliar";
    END IF;
END$$

USE `mydb_Catastro`$$
CREATE DEFINER = CURRENT_USER TRIGGER `mydb_Catastro`.`PersonaViveUnifamiliar_BEFORE_INSERT` BEFORE INSERT ON `PersonaViveUnifamiliar` FOR EACH ROW
BEGIN
	IF (NEW.DNI IN (SELECT DNI
		FROM PersonaVivePiso)) THEN
			SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = "La persona con el DNI añadido ya vive en un piso";
    END IF;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
