-- MySQL Script generated by MySQL Workbench
-- Sun Nov 15 13:26:18 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Vivero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vivero` (
  `Ubicación` VARCHAR(80) NOT NULL,
  `Hora Apertura` DATETIME NOT NULL,
  `Hora Cierre` DATETIME NOT NULL,
  PRIMARY KEY (`Ubicación`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Zona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Zona` (
  `Numero Zona` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Ubicación` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`Numero Zona`, `Ubicación`),
  INDEX `UbicaciónVivero_idx` (`Ubicación` ASC) VISIBLE,
  CONSTRAINT `UbicaciónVivero`
    FOREIGN KEY (`Ubicación`)
    REFERENCES `mydb`.`Vivero` (`Ubicación`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empleado` (
  `DNI` VARCHAR(9) NOT NULL,
  `CódigoSeguridadSocial` VARCHAR(45) NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`DNI`, `CódigoSeguridadSocial`),
  UNIQUE INDEX `DNI_UNIQUE` (`DNI` ASC) VISIBLE,
  UNIQUE INDEX `CódigoSeguridadSocial_UNIQUE` (`CódigoSeguridadSocial` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Zona_Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Zona_Empleado` (
  `NumeroZona` INT NOT NULL,
  `DNI Empleado` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`NumeroZona`, `DNI Empleado`),
  INDEX `DNI_idx` (`DNI Empleado` ASC) VISIBLE,
  CONSTRAINT `NumeroZona`
    FOREIGN KEY (`NumeroZona`)
    REFERENCES `mydb`.`Zona` (`Numero Zona`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT,
  CONSTRAINT `DNI`
    FOREIGN KEY (`DNI Empleado`)
    REFERENCES `mydb`.`Empleado` (`DNI`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Productos` (
  `CódigoBarras` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Precio` INT NULL,
  `Tipo` VARCHAR(45) NULL,
  `Stock` INT NULL,
  PRIMARY KEY (`CódigoBarras`),
  UNIQUE INDEX `CódigoBarras_UNIQUE` (`CódigoBarras` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Zona_Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Zona_Producto` (
  `NumeroZona` INT NOT NULL,
  `CódigoBarras` INT NOT NULL,
  `Cantidad` INT NULL,
  PRIMARY KEY (`NumeroZona`, `CódigoBarras`),
  INDEX `Producto_idx` (`CódigoBarras` ASC) VISIBLE,
  CONSTRAINT `Zona`
    FOREIGN KEY (`NumeroZona`)
    REFERENCES `mydb`.`Zona` (`Numero Zona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Producto`
    FOREIGN KEY (`CódigoBarras`)
    REFERENCES `mydb`.`Productos` (`CódigoBarras`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `DNI` VARCHAR(9) NOT NULL,
  `IdSocio` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Bonificación` INT NOT NULL,
  `GastoMensual` INT ZEROFILL NULL,
  `Apellido1` VARCHAR(45) NOT NULL,
  `Apellido2` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NULL,
  PRIMARY KEY (`DNI`, `IdSocio`),
  UNIQUE INDEX `DNI_UNIQUE` (`DNI` ASC) VISIBLE,
  UNIQUE INDEX `IdSocio_UNIQUE` (`IdSocio` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pedido` (
  `ID` INT NOT NULL,
  `DNI Cliente` VARCHAR(9) NOT NULL,
  `DNI Empleado` VARCHAR(9) NOT NULL,
  `Fecha` DATE NOT NULL,
  `Importe` INT NULL,
  PRIMARY KEY (`ID`, `DNI Cliente`, `DNI Empleado`),
  INDEX `DNI_idx` (`DNI Cliente` ASC) VISIBLE,
  INDEX `DNI Empleado Gestor_idx` (`DNI Empleado` ASC) VISIBLE,
  CONSTRAINT `DNI`
    FOREIGN KEY (`DNI Cliente`)
    REFERENCES `mydb`.`Cliente` (`DNI`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `DNI Empleado Gestor`
    FOREIGN KEY (`DNI Empleado`)
    REFERENCES `mydb`.`Empleado` (`DNI`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Producto_Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Producto_Pedido` (
  `CódigoBarras` INT NOT NULL,
  `ID Pedido` INT NOT NULL,
  `Cantidad` INT NOT NULL,
  PRIMARY KEY (`CódigoBarras`, `ID Pedido`),
  INDEX `ID_idx` (`ID Pedido` ASC) VISIBLE,
  CONSTRAINT `CodigoBarras`
    FOREIGN KEY (`CódigoBarras`)
    REFERENCES `mydb`.`Productos` (`CódigoBarras`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `ID`
    FOREIGN KEY (`ID Pedido`)
    REFERENCES `mydb`.`Pedido` (`ID`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;

USE `mydb` ;

-- -----------------------------------------------------
-- procedure crear_email
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE PROCEDURE `crear_email` (IN dominio VARCHAR(45))
BEGIN
	IF NEW.Email = null THEN
    SET NEW.Email = CONCAT(LEFT(NEW.Nombre, 3), LEFT(NEW.Apellido1, 3), LEFT(NEW.Apellido2, 3), '@', dominio);
    END IF;
END$$

DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
USE `mydb`;

DELIMITER $$
USE `mydb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `mydb`.`trigger_crear_email_before_insert` BEFORE INSERT ON `Cliente` FOR EACH ROW
BEGIN
	CALL crear_email('viveros.ull.es');
END$$

USE `mydb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `mydb`.`Producto_Pedido_AFTER_INSERT` AFTER INSERT ON `Producto_Pedido` FOR EACH ROW
BEGIN
	Update Productos
    set Productos.Stock = Productos.Stock - NEW.Cantidad
    where Productos.CódigoBarras = NEW.CódigoBarras;
END$$


DELIMITER ;
